ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import (index, contact, NewItems,
    WestFjordsCollection, EastFjordsCollection,
    Reykjalife, HellaMornings, Jackets, RainCoats,
    TeesandTops, Glasses, Comfort, Sweaters,
                        HatsandScarves)

from item.views import cart, add_to_cart
from search.views import SearchView
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path as url
from django.urls import path
from search import views
urlpatterns = [


              #  path('cart', cart, name = 'cart'),

                #  path("add_to_cart", add_to_cart, name="add"),
#
                  #  path('search/', SearchView, name='search'),
                  path('', index, name='index'),
                  path('items/', include('item.urls')),
    path('contact/', contact, name='contact'),
    path('admin/', admin.site.urls),

    path('NewItems/', NewItems, name = 'NewItems'),
    path('WestFjordsCollection/', WestFjordsCollection, name='WestFjordsCollection'),
    path('EastFjordsCollection/', EastFjordsCollection, name='EastFjordsCollection'),
    path('Reykjalife/', Reykjalife, name='Reykjalife'),
    path('HellaMornings/', HellaMornings, name='HellaMornings'),

    path('Jackets/', Jackets, name='Jackets'),
                  path('RainCoats/', RainCoats, name='RainCoats'),
                  path('Sweaters/', Sweaters, name='Sweaters'),
                  path('TeesandTops/', TeesandTops, name='TeesandTops'),
                  path('Glasses/', Glasses, name='Glasses'),
                  path('Comfort/', Comfort, name='Comfort'),
                  path('HatsandScarves/', HatsandScarves, name='HatsandScarves'),

              ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecom/item/urls.py
from django.urls import path
from . import views
from django.urls import re_path as url
app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    ]

ecom/core/models.py
from django.db import models
# Create your models here.

ecom/core/views.py
from django.shortcuts import render
from item.models import Category, Item, Collections
from django.db.models import Q
from django.db.models.functions import Lower


def index(request):
    if 'q' in request.GET:
        q = request.GET['q']
        q = q.lower()
        # data = Item.objects.get(category=q)

        name = Lower(Category.objects.filter(name__icontains=q).values_list('id'))
        data = Item.objects.filter(Q(category__in=name) |
                                   Q(collections__in=name))
        if len(data) == 0:
            data = Item.objects.exclude(Q(category=9))
            name = Category.objects.exclude(name='glasses').values_list('id', flat=True)
            return render(request, 'core/searchindex.html', {
                'data':data
            })
        else:
            return render(request, 'core/searchindex.html', context={'data': data, })

    else:
        items = Item.objects.filter(is_featured=True)
        categories = Category.objects.all()

        return render(request, 'core/index.html', {
            'categories': categories,
            'items': items,
        })

def NewItems(request):
    if 'q' in request.GET:
        q = request.GET['q']
        q = q.lower()
        # data = Item.objects.get(category=q)

        name = Lower(Category.objects.filter(name__icontains=q).values_list('id'))
        data = Item.objects.filter(Q(category__in=name) | Q(collections__in=name))
        if len(data) == 0:
            data = Item.objects.exclude(Q(category=9))
            return render(request, 'core/searchindex.html', {
                'data': data
            })
        else:
            return render(request, 'core/searchindex.html', context={'data': data, })
    else:
        items = Item.objects.filter(is_new=True)
        categories = Category.objects.all()
        return render(request, 'core/NewItems.html', {
            'categories': categories,
            'items': items,
        })
def WestFjordsCollection(request):
    items = Item.objects.filter(collections__name='West Fjords')
    collections = Collections.objects.all()
    context = {
        'collections': collections,
        'items': items,
    }
    return render(request, 'core/WestFjordsCollection.html', context)
def EastFjordsCollection(request):
    items = Item.objects.filter(collections__name='East Fjords')
    collections = Collections.objects.all()
    context = {
        'collections':collections,
        'items':items,
    }
    return render(request, 'core/EastFjordsCollection.html', context)
def Reykjalife(request):
    items = Item.objects.filter(collections__name='Reykjalife')
    collections = Collections.objects.all()
    context = {
        'collections':collections,
        'items':items,
    }
    return render(request, 'core/Reykjalife.html', context)

def HellaMornings(request):
    items = Item.objects.filter(collections__name='Hella Mornings')
    collections = Collections.objects.all()
    context = {
        'collections':collections,
        'items':items,
    }
    return render(request, 'core/HellaMornings.html', context)


def Jackets(request):
    if 'q' in request.GET:
        q = request.GET['q']
        q = q.lower()
        # data = Item.objects.get(category=q)

        name = Lower(Category.objects.filter(name__icontains=q).values_list('id'))
        data = Item.objects.filter(Q(category__in=name) |  Q(collections__in=name))
        if len(data) == 0:
            data = Item.objects.exclude(Q(category=9))
            return render(request, 'core/searchindex.html', {
                'data': data
            })
        else:
            return render(request, 'core/searchindex.html', context={'data': data, })
    else:
        items = Item.objects.filter(category__name='jackets')
        categories = Category.objects.all()
        return render(request, 'core/Jackets.html', {
            'categories': categories,
            'items': items,
        })

def RainCoats(request):
    if 'q' in request.GET:
        q = request.GET['q']
        q = q.lower()
        # data = Item.objects.get(category=q)

        name = Lower(Category.objects.filter(name__icontains=q).values_list('id'))
        data = Item.objects.filter(Q(category__in=name) |  Q(collections__in=name))
        if len(data) == 0:
            data = Item.objects.exclude(Q(category=9))
            return render(request, 'core/searchindex.html', {
                'data': data
            })
        else:
            return render(request, 'core/searchindex.html', context={'data': data, })
    else:
        items = Item.objects.filter(category__name='rain coats')
        categories = Category.objects.all()
        return render(request, 'core/RainCoats.html', {
            'categories': categories,
            'items': items,
        })
def TeesandTops(request):
    if 'q' in request.GET:
        q = request.GET['q']
        q = q.lower()
        # data = Item.objects.get(category=q)

        name = Lower(Category.objects.filter(name__icontains=q).values_list('id'))
        data = Item.objects.filter(Q(category__in=name) | Q(collections__in=name))
        if len(data) == 0:
            data = Item.objects.exclude(Q(category=9))
            return render(request, 'core/searchindex.html', {
                'data': data
            })
        else:
            return render(request, 'core/searchindex.html', context={'data': data, })
    else:
        items = Item.objects.filter(category__name='shirts')
        categories = Category.objects.all()
        return render(request, 'core/TeesandTops.html', {
            'categories': categories,
            'items': items,
        })

def Glasses(request):
    if 'q' in request.GET:
        q = request.GET['q']
        q = q.lower()
        name = Lower(Category.objects.filter(name__icontains=q).values_list('id'))
        data = Item.objects.filter(Q(category__in=name) |  Q(collections__in=name))
        if len(data) == 0:
            data = Item.objects.exclude(Q(category=9))
            return render(request, 'core/searchindex.html', {
                'data': data
            })
        else:
            return render(request, 'core/searchindex.html', context={'data': data, })
    else:
        items = Item.objects.filter(category__name='glasses')
        categories = Category.objects.all()
        return render(request, 'core/Glasses.html', {
            'categories': categories,
            'items': items,
        })
def Comfort(request):
    if 'q' in request.GET:
        q = request.GET['q']
        q = q.lower()
        # data = Item.objects.get(category=q)

        name = Lower(Category.objects.filter(name__icontains=q).values_list('id'))
        data = Item.objects.filter(Q(category__in=name) |  Q(collections__in=name))
        if len(data) == 0:
            data = Item.objects.exclude(Q(category=9))
            return render(request, 'core/searchindex.html', {
                'data': data
            })
        else:
            return render(request, 'core/searchindex.html', context={'data': data, })
    else:
        items = Item.objects.filter(category__name='comfort')
        categories = Category.objects.all()
        return render(request, 'core/Comfort.html', {
            'categories': categories,
            'items': items,
        })

def Sweaters(request):
    if 'q' in request.GET:
        q = request.GET['q']
        q = q.lower()
        # data = Item.objects.get(category=q)

        name = Lower(Category.objects.filter(name__icontains=q).values_list('id'))
        data = Item.objects.filter(Q(category__in=name) |  Q(collections__in=name))
        if len(data) == 0:
            data = Item.objects.exclude(Q(category=9))
            return render(request, 'core/searchindex.html', {
                'data': data
            })
        else:
            return render(request, 'core/searchindex.html', context={'data': data, })
    else:
        items = Item.objects.filter(category__name='sweaters')
        categories = Category.objects.all()
        return render(request, 'core/Sweaters.html', {
            'categories': categories,
            'items': items,
        })
def HatsandScarves(request):
    if 'q' in request.GET:
        q = request.GET['q']
        q = q.lower()
        # data = Item.objects.get(category=q)

        name = Lower(Category.objects.filter(name__icontains=q).values_list('id'))
        data = Item.objects.filter(Q(category__in=name) |  Q(collections__in=name))
        if len(data) == 0:
            data = Item.objects.exclude(Q(category=9))
            return render(request, 'core/searchindex.html', {
                'data': data
            })
        else:
            return render(request, 'core/searchindex.html', context={'data': data, })
    else:
        items = Item.objects.filter(category__name='hats and scarves')
        categories = Category.objects.all()
        return render(request, 'core/HatsandScarves.html', {
            'categories': categories,
            'items': items,
        })




def contact(request):
    return render(request, 'core/contact.html')

ecom/core/templates/core/HellaMornings.html
{% extends 'core/base2.html' %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'index_style.css' %}">



<a>
    <center>

        <style>
            .grad1 img {
    -webkit-mask-image:-webkit-gradient(linear, left top, left bottom, from(rgba(0,0,0,1)), to(rgba(.8,.8,.8,.8)))
  }
        </style>
    <div class = "grad1">
    <img src=" {% static 'ice.webp' %}" style = 'margin-bottom:3%;width:90%;height:880px;position:relative;top:-20px;left:0px;z-index:-1;box-shadow:0px 0px 64px 0px rgba(0,0,0,0,.72);border-radius:30px;'>
             </div>

        <style>
            html, body {
	width:100%;
	height:100%;
}
body {
    margin: 0;
    padding: 0;
    font-family: sans-serif;

}
.box {
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%,-50%);
	width: 400px;
	padding: 40px;
	background: rgba(0,0,0,.4);
	box-sizing: border-box;
	box-shadow: 0 15px 25px rgba(0,0,0,.5);
	border-radius: 10px;
}
.box h2 {
	margin: 0 0 30px;
	padding: 0;
	color: #FFF;
	text-align: center;
}

.box .inputBox {
	position: relative;
}
.box .inputBox input {
	width: 100%;
	padding: 10px 0;
	font-size: 16px;
	color: #FFF;
	letter-spacing: 1px;
	margin-bottom: 30px;
	border: none;
	border-bottom: 1px solid #FFF;
	outline: none;
	background: transparent;
}
.box .inputBox label {
	position: absolute;
	top: 0;
	left: 0;
	padding: 10px 0;
	font-size: 16px;
	color: #FFF;
	pointer-events: none;
	transition: .5s;
	animation: LabelOnLoad 1s forwards 0s ease;
}
@keyframes LabelOnLoad{
    0%{
        transform: rotate(0) translateY(-19px);
        opacity: 0;
        }
    100%{
        transform: rotate(0) translateY(0);
        opacity: 1;
        }
}
.box .inputBox input:focus ~ label,
.box .inputBox input:valid ~ label {
	top: -19px;
	left:0;
	color: #03A9F4;
	font-size: 12px;
}
.box input[type='submit'] {
	background: transparent;
	border: none;
	outline: none;
	color: #FFF;
	background: #03A9F4;
	padding: 10px 20px;
	cursor: pointer;
	border-radius: 5px;
	font-size: 14px;
}
.box input[type='submit']:hover {
	background-color: rgba(3, 169, 244, 0.7);
}
@media(max-width: 720px){
	.box {
		width: 80%;
	}
}

.fade-in-image {
    -webkit-animation: 3s ease 3s normal forwards 1 fadein;
    animation: 3s ease 0s normal forwards 1 fadein;
    position:absolute;
}

@keyframes fadein {
  0% {opacity:0;}
  100% {opacity:1;}
}


@-webkit-keyframes fadein {
  0% {opacity:0;}
  100% {opacity:1;}
}
        </style>


        	<div class="box" style = 'margin-left:-25%;margin-top:8%;'>
		<h2>Subscribe to Hella Mornings Style</h2>
		<form action="">
			<div class="inputBox">
				<input type="text" name="" required="">
				<label for="">Email</label>
			</div>

			<input type="submit" name="" value="Submit">
		</form>
	</div>








        </center>
</a>

<body>
   <div class="mt-6 px-6 py-6 py-12 bg-gray-100 rounded-xl">
        <h2 class = "mb-12 text-2xl text-center" style = "position:relative;top:-80px; left:-20px; margin-bottom:20px;background-color-white;">East Fjords Collection</h2>
        <div class = "grid grid-cols-3 gap-3" style = 'margin-top:10px;'>
            {% for item in items %}
            <div style = 'margin-bottom:40px;'>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <center>
                        <img src="{{ item.image.url }}" class = "rounded-t-xl">
                            </center>
                    </div>

                    <div class="p-6 bg-white rounded-b-xl" style = 'height:55px;width:auto;'>
                        <p class="text-2l" style = 'margin-top:-4.0%;'>{{ item.name }}</p>
                        <p class = "text-gray-500" style = 'margin-top:-1%;'>Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
        </div>
    </div>

    </body>

{% endblock %}

ecom/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center" style = 'height:52px;background-color:transparent;position:absolute;z-index:5;width:100%;   color: white;'>
            <a href="/" class="text-xl font-semibold">Iceland Wares</a>

            <div class="space-x-6" style = 'margin-right:5%;'>
                <a href="/" class="text-lg font-semibold hover:text-gray-500" style = 'margin-right:30px;'>Home</a>
                <a href="#" class="text-lg font-semibold hover:text-gray-500" style = 'margin-right:30px;'>Explore</a>
                                <a href="#" class="text-lg font-semibold hover:text-gray-500">Subscribe</a>



            </div>
        </nav>
        <div class = "px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
        <footer class="py-2 px-6 flex justify-between bg-gray-800" style = 'margin-top:-1%;width:200vh;margin-left:-3%;margin-bottom:-50px;'>
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">Learn More</h3>

                <p class="text-lg text-gray-500"> Some Text for you Some Text for you Some Text for you</p>

            </div>
            <div class="w-1/3" style = 'margin-left:35%;'>
                                <ul class="space-y-2" style = 'margin-top:6.3%;'>

                    <li><a href="{% url 'index' %}" class="text-lg text-teal-500 hover:text-teal-600">Home</a></li>
                </ul>
            </div>
                      <div class="w-1/3" style = 'margin-left:-13.5%;'>
                <ul class="space-y-2" style = 'margin-top:6.3%;'>
                                        <li><a href="{% url 'index' %}" class="text-lg text-teal-500 hover:text-teal-600">Contact</a></li>
                </ul>
            </div>
                      <div class="w-1/3" style = 'margin-left:-12.5%;'>
                <ul class="space-y-2" style = 'margin-top:6.3%;'>
                                        <li><a href="{% url 'index' %}" class="text-lg text-teal-500 hover:text-teal-600">About Me</a></li>
                </ul>
            </div>

        </footer>
    </body>
</html>

ecom/core/templates/core/cart.html
{% extends 'core/base5.html' %} {% block content %}

<div class="shoppingCart">
  <h2>My Cart</h2>

  <div class="heading">
    <div class="p_name"><h4>Product's Name</h4></div>
    <div class="name"><h4>Quantity</h4></div>
    <div class="name"><h4>Unit Price</h4></div>
    <div class="name"><h4>Prize</h4></div>
  </div>

  <div class="itemContainer">

    {% for item in cart.cartitems.all %}
    <div class="item">
      <div class="iteminfo">
        <div class="p_img">
          <img src="{{item.product.image.url}}" alt="" />
        </div>
        <p>{{item.product.name}}</p>
      </div>

      <div class="name"><p>{{item.quantity}}</p></div>
      <div class="name"><p>${{item.product.price}}</p></div>
      <div class="name"><p>${{item.price}}</p></div>
    </div>

    {% endfor %}
  </div>

  <div class="pay-section">
    <h3>Grand-Total: ${{cart.total_price}}</h3>
    <button onclick = "makePayment()" >Pay</button>
  </div>
</div>

<script src="https://checkout.flutterwave.com/v3.js"></script>
<script>

let cart_total = "{{cart.total_price}}"
let cart_id = "{{cart.id}}"


  function makePayment() {
    FlutterwaveCheckout({
      public_key: "FLWPUBK_TEST-PUBLIC KEY",
      tx_ref: "titanic-48981487343MDI0NzMx",
      amount: cart_total,
      currency: "USD",
      payment_options: "card, mobilemoneyghana, ussd",
      redirect_url: "http://127.0.0.1:8000/confirm_payment/"+cart_id,
      meta: {
        consumer_id: 23,
        consumer_mac: "92a3-912ba-1192a",
      },
      customer: {
        email: "rose@unsinkableship.com",
        phone_number: "08102909304",
        name: "{{request.user.username}}",
      },
      customizations: {
        title: "My Shop",
        description: "Buy with ease",
        logo: "https://www.logolynx.com/images/logolynx/22/2239ca38f5505fbfce7e55bbc0604386.jpeg",
      },
    });
  }

</script>

{% endblock content %}

ecom/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1> Contact Us</h1>
{% endblock %}